---
- include_tasks: morpheus_packages.yml
  when: ansible_distribution == "CentOS"

- include_tasks: morpheus_packages_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: morpheus_configure.yml

- include_tasks: morpheus_reconfigure.yml