---

- name: Add Erlang Solutions repository
  apt_repository:
    repo: '{{ ubuntu_erlang_repo }}'
    state: present
    
- name: Update cache
  apt:
    update_cache: yes

- name: Install erlang
  apt:
    name: erlang
    
- name: Install SoCat
  apt: 
    name: socat