---

- name: rabbitmq_ha_config | creating vhost
  rabbitmq_vhost:
      name: "{{ vhost_name }}"
  when: inventory_hostname == "{{ groups['rabbit'][0] }}"

- name: rabbitmq_ha_config | creating user
  rabbitmq_user:
      user: "{{ rabbitmq_user }}"
      password: "{{ rabbitmq_password }}"
      permissions:
          - vhost: "{{ vhost_name }}"
            configure_priv: .*
            read_priv: .*
            write_priv: .*
      state: present
  when: inventory_hostname == "{{ groups['rabbit'][0] }}"

- name: rabbitmq_ha_config | setting up ha on queue(s)
  rabbitmq_policy: name='ha-all' pattern='.*' vhost='{{ vhost_name }}' tags="{{ tags }}" state=present
  run_once: true
  when: inventory_hostname == "{{ groups['rabbit'][0] }}"